namespace KTV
{
    partial class Main
    {
        /// <summary>
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows 窗体设计器生成的代码

        /// <summary>
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.bntAuDelete = new System.Windows.Forms.Button();
            this.bntAuUpdate = new System.Windows.Forms.Button();
            this.bntAut = new System.Windows.Forms.Button();
            this.lvAuton = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader2 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader3 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader4 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader5 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader6 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader24 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.bntMuserDelete = new System.Windows.Forms.Button();
            this.bntMuserUpdate = new System.Windows.Forms.Button();
            this.bntMuserAdd = new System.Windows.Forms.Button();
            this.lvMuscie = new System.Windows.Forms.ListView();
            this.columnHeader16 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader17 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader18 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader19 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader20 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader21 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.lvDitcy = new System.Windows.Forms.ListView();
            this.columnHeader7 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader8 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader9 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.bntSave = new System.Windows.Forms.Button();
            this.bntUserDelete = new System.Windows.Forms.Button();
            this.bntUserUpdate = new System.Windows.Forms.Button();
            this.bntUserAdd = new System.Windows.Forms.Button();
            this.txtPassWord = new System.Windows.Forms.TextBox();
            this.txtUser = new System.Windows.Forms.TextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.LvUser = new System.Windows.Forms.ListView();
            this.columnHeader22 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader23 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader10 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader11 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader12 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader13 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader14 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeader15 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.button4 = new System.Windows.Forms.Button();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Location = new System.Drawing.Point(12, 12);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(553, 284);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.bntAuDelete);
            this.tabPage1.Controls.Add(this.bntAuUpdate);
            this.tabPage1.Controls.Add(this.bntAut);
            this.tabPage1.Controls.Add(this.lvAuton);
            this.tabPage1.Location = new System.Drawing.Point(4, 21);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(545, 259);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "明星信息";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage1.Click += new System.EventHandler(this.tabPage1_Click);
            // 
            // bntAuDelete
            // 
            this.bntAuDelete.Location = new System.Drawing.Point(351, 233);
            this.bntAuDelete.Name = "bntAuDelete";
            this.bntAuDelete.Size = new System.Drawing.Size(75, 23);
            this.bntAuDelete.TabIndex = 3;
            this.bntAuDelete.Text = "删除(&E)";
            this.bntAuDelete.UseVisualStyleBackColor = true;
            this.bntAuDelete.Click += new System.EventHandler(this.bntAuDelete_Click);
            // 
            // bntAuUpdate
            // 
            this.bntAuUpdate.Location = new System.Drawing.Point(213, 233);
            this.bntAuUpdate.Name = "bntAuUpdate";
            this.bntAuUpdate.Size = new System.Drawing.Size(75, 23);
            this.bntAuUpdate.TabIndex = 2;
            this.bntAuUpdate.Text = "修改(&F)";
            this.bntAuUpdate.UseVisualStyleBackColor = true;
            this.bntAuUpdate.Click += new System.EventHandler(this.bntAuUpdate_Click);
            // 
            // bntAut
            // 
            this.bntAut.Location = new System.Drawing.Point(66, 233);
            this.bntAut.Name = "bntAut";
            this.bntAut.Size = new System.Drawing.Size(75, 23);
            this.bntAut.TabIndex = 1;
            this.bntAut.Text = "添加(&D)";
            this.bntAut.UseVisualStyleBackColor = true;
            this.bntAut.Click += new System.EventHandler(this.bntAut_Click);
            // 
            // lvAuton
            // 
            this.lvAuton.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1,
            this.columnHeader2,
            this.columnHeader3,
            this.columnHeader4,
            this.columnHeader5,
            this.columnHeader6,
            this.columnHeader24});
            this.lvAuton.FullRowSelect = true;
            this.lvAuton.GridLines = true;
            this.lvAuton.Location = new System.Drawing.Point(6, 6);
            this.lvAuton.MultiSelect = false;
            this.lvAuton.Name = "lvAuton";
            this.lvAuton.Size = new System.Drawing.Size(516, 213);
            this.lvAuton.TabIndex = 0;
            this.lvAuton.UseCompatibleStateImageBehavior = false;
            this.lvAuton.View = System.Windows.Forms.View.Details;
            this.lvAuton.Click += new System.EventHandler(this.lvAuton_Click);
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "明星编号";
            this.columnHeader1.Width = 140;
            // 
            // columnHeader2
            // 
            this.columnHeader2.Text = "明星姓名";
            this.columnHeader2.Width = 100;
            // 
            // columnHeader3
            // 
            this.columnHeader3.Text = "性别";
            // 
            // columnHeader4
            // 
            this.columnHeader4.Text = "国籍";
            // 
            // columnHeader5
            // 
            this.columnHeader5.Text = "明星类型";
            this.columnHeader5.Width = 81;
            // 
            // columnHeader6
            // 
            this.columnHeader6.Text = "出生日期";
            this.columnHeader6.Width = 100;
            // 
            // columnHeader24
            // 
            this.columnHeader24.Text = "备注";
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.bntMuserDelete);
            this.tabPage2.Controls.Add(this.bntMuserUpdate);
            this.tabPage2.Controls.Add(this.bntMuserAdd);
            this.tabPage2.Controls.Add(this.lvMuscie);
            this.tabPage2.Location = new System.Drawing.Point(4, 21);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(545, 259);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "歌曲信息";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // bntMuserDelete
            // 
            this.bntMuserDelete.Location = new System.Drawing.Point(398, 225);
            this.bntMuserDelete.Name = "bntMuserDelete";
            this.bntMuserDelete.Size = new System.Drawing.Size(93, 23);
            this.bntMuserDelete.TabIndex = 8;
            this.bntMuserDelete.Text = "删除(&E)";
            this.bntMuserDelete.UseVisualStyleBackColor = true;
            this.bntMuserDelete.Click += new System.EventHandler(this.bntMuserDelete_Click);
            // 
            // bntMuserUpdate
            // 
            this.bntMuserUpdate.Location = new System.Drawing.Point(244, 225);
            this.bntMuserUpdate.Name = "bntMuserUpdate";
            this.bntMuserUpdate.Size = new System.Drawing.Size(93, 23);
            this.bntMuserUpdate.TabIndex = 7;
            this.bntMuserUpdate.Text = "修改(&F)";
            this.bntMuserUpdate.UseVisualStyleBackColor = true;
            this.bntMuserUpdate.Click += new System.EventHandler(this.bntMuserUpdate_Click);
            // 
            // bntMuserAdd
            // 
            this.bntMuserAdd.Location = new System.Drawing.Point(91, 225);
            this.bntMuserAdd.Name = "bntMuserAdd";
            this.bntMuserAdd.Size = new System.Drawing.Size(93, 23);
            this.bntMuserAdd.TabIndex = 6;
            this.bntMuserAdd.Text = "添加（&D)";
            this.bntMuserAdd.UseVisualStyleBackColor = true;
            this.bntMuserAdd.Click += new System.EventHandler(this.bntMuserAdd_Click);
            // 
            // lvMuscie
            // 
            this.lvMuscie.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader16,
            this.columnHeader17,
            this.columnHeader18,
            this.columnHeader19,
            this.columnHeader20,
            this.columnHeader21});
            this.lvMuscie.FullRowSelect = true;
            this.lvMuscie.GridLines = true;
            this.lvMuscie.Location = new System.Drawing.Point(6, 6);
            this.lvMuscie.MultiSelect = false;
            this.lvMuscie.Name = "lvMuscie";
            this.lvMuscie.Size = new System.Drawing.Size(524, 213);
            this.lvMuscie.TabIndex = 5;
            this.lvMuscie.UseCompatibleStateImageBehavior = false;
            this.lvMuscie.View = System.Windows.Forms.View.Details;
            this.lvMuscie.MouseClick += new System.Windows.Forms.MouseEventHandler(this.lvMuscie_MouseClick);
            // 
            // columnHeader16
            // 
            this.columnHeader16.Text = "编号";
            this.columnHeader16.Width = 40;
            // 
            // columnHeader17
            // 
            this.columnHeader17.Text = "歌曲名称";
            this.columnHeader17.Width = 100;
            // 
            // columnHeader18
            // 
            this.columnHeader18.Text = "演唱者";
            // 
            // columnHeader19
            // 
            this.columnHeader19.Text = "类型";
            this.columnHeader19.Width = 79;
            // 
            // columnHeader20
            // 
            this.columnHeader20.Text = "语言";
            this.columnHeader20.Width = 87;
            // 
            // columnHeader21
            // 
            this.columnHeader21.Text = "文件位置";
            this.columnHeader21.Width = 149;
            // 
            // tabPage3
            // 
            this.tabPage3.Controls.Add(this.button1);
            this.tabPage3.Controls.Add(this.button2);
            this.tabPage3.Controls.Add(this.button3);
            this.tabPage3.Controls.Add(this.lvDitcy);
            this.tabPage3.Location = new System.Drawing.Point(4, 21);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Size = new System.Drawing.Size(545, 259);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "歌曲类型信息";
            this.tabPage3.UseVisualStyleBackColor = true;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(332, 200);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 7;
            this.button1.Text = "删除(&E)";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click_1);
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(332, 97);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 6;
            this.button2.Text = "修改(&F)";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(332, 10);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(75, 23);
            this.button3.TabIndex = 5;
            this.button3.Text = "添加(&D)";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // lvDitcy
            // 
            this.lvDitcy.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader7,
            this.columnHeader8,
            this.columnHeader9});
            this.lvDitcy.FullRowSelect = true;
            this.lvDitcy.GridLines = true;
            this.lvDitcy.Location = new System.Drawing.Point(30, 10);
            this.lvDitcy.MultiSelect = false;
            this.lvDitcy.Name = "lvDitcy";
            this.lvDitcy.Size = new System.Drawing.Size(287, 213);
            this.lvDitcy.TabIndex = 4;
            this.lvDitcy.UseCompatibleStateImageBehavior = false;
            this.lvDitcy.View = System.Windows.Forms.View.Details;
            this.lvDitcy.Click += new System.EventHandler(this.lvDitcy_Click);
            // 
            // columnHeader7
            // 
            this.columnHeader7.Text = "类型编号";
            this.columnHeader7.Width = 120;
            // 
            // columnHeader8
            // 
            this.columnHeader8.Text = "歌曲类型 ";
            this.columnHeader8.Width = 100;
            // 
            // columnHeader9
            // 
            this.columnHeader9.Text = "备注";
            // 
            // tabPage4
            // 
            this.tabPage4.Controls.Add(this.bntSave);
            this.tabPage4.Controls.Add(this.bntUserDelete);
            this.tabPage4.Controls.Add(this.bntUserUpdate);
            this.tabPage4.Controls.Add(this.bntUserAdd);
            this.tabPage4.Controls.Add(this.txtPassWord);
            this.tabPage4.Controls.Add(this.txtUser);
            this.tabPage4.Controls.Add(this.label2);
            this.tabPage4.Controls.Add(this.label1);
            this.tabPage4.Controls.Add(this.LvUser);
            this.tabPage4.Location = new System.Drawing.Point(4, 21);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Size = new System.Drawing.Size(545, 259);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "用户管理";
            this.tabPage4.UseVisualStyleBackColor = true;
            // 
            // bntSave
            // 
            this.bntSave.Location = new System.Drawing.Point(453, 148);
            this.bntSave.Name = "bntSave";
            this.bntSave.Size = new System.Drawing.Size(63, 23);
            this.bntSave.TabIndex = 8;
            this.bntSave.Text = "保存(&O)";
            this.bntSave.UseVisualStyleBackColor = true;
            this.bntSave.Click += new System.EventHandler(this.bntSave_Click);
            // 
            // bntUserDelete
            // 
            this.bntUserDelete.Location = new System.Drawing.Point(384, 148);
            this.bntUserDelete.Name = "bntUserDelete";
            this.bntUserDelete.Size = new System.Drawing.Size(63, 23);
            this.bntUserDelete.TabIndex = 7;
            this.bntUserDelete.Text = "删除(&E)";
            this.bntUserDelete.UseVisualStyleBackColor = true;
            this.bntUserDelete.Click += new System.EventHandler(this.bntUserDelete_Click);
            // 
            // bntUserUpdate
            // 
            this.bntUserUpdate.Location = new System.Drawing.Point(298, 148);
            this.bntUserUpdate.Name = "bntUserUpdate";
            this.bntUserUpdate.Size = new System.Drawing.Size(63, 23);
            this.bntUserUpdate.TabIndex = 6;
            this.bntUserUpdate.Text = "修改(&F)";
            this.bntUserUpdate.UseVisualStyleBackColor = true;
            this.bntUserUpdate.Click += new System.EventHandler(this.bntUserUpdate_Click);
            // 
            // bntUserAdd
            // 
            this.bntUserAdd.Location = new System.Drawing.Point(229, 148);
            this.bntUserAdd.Name = "bntUserAdd";
            this.bntUserAdd.Size = new System.Drawing.Size(63, 23);
            this.bntUserAdd.TabIndex = 5;
            this.bntUserAdd.Text = "添加(&D)";
            this.bntUserAdd.UseVisualStyleBackColor = true;
            this.bntUserAdd.Click += new System.EventHandler(this.bntUserAdd_Click);
            // 
            // txtPassWord
            // 
            this.txtPassWord.Location = new System.Drawing.Point(283, 91);
            this.txtPassWord.MaxLength = 30;
            this.txtPassWord.Name = "txtPassWord";
            this.txtPassWord.PasswordChar = '*';
            this.txtPassWord.Size = new System.Drawing.Size(233, 21);
            this.txtPassWord.TabIndex = 4;
            // 
            // txtUser
            // 
            this.txtUser.Location = new System.Drawing.Point(283, 51);
            this.txtUser.MaxLength = 40;
            this.txtUser.Name = "txtUser";
            this.txtUser.Size = new System.Drawing.Size(233, 21);
            this.txtUser.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(209, 94);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(65, 12);
            this.label2.TabIndex = 2;
            this.label2.Text = "用户密码：";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(209, 54);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(65, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "用户姓名：";
            // 
            // LvUser
            // 
            this.LvUser.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader22,
            this.columnHeader23});
            this.LvUser.FullRowSelect = true;
            this.LvUser.GridLines = true;
            this.LvUser.Location = new System.Drawing.Point(26, 20);
            this.LvUser.Name = "LvUser";
            this.LvUser.Size = new System.Drawing.Size(165, 211);
            this.LvUser.TabIndex = 0;
            this.LvUser.UseCompatibleStateImageBehavior = false;
            this.LvUser.View = System.Windows.Forms.View.Details;
            this.LvUser.Click += new System.EventHandler(this.LvUser_Click);
            // 
            // columnHeader22
            // 
            this.columnHeader22.Text = "用户编号";
            this.columnHeader22.Width = 100;
            // 
            // columnHeader23
            // 
            this.columnHeader23.Text = "用户姓名";
            // 
            // columnHeader10
            // 
            this.columnHeader10.Text = "明星编号";
            this.columnHeader10.Width = 140;
            // 
            // columnHeader11
            // 
            this.columnHeader11.Text = "明星姓名";
            this.columnHeader11.Width = 100;
            // 
            // columnHeader12
            // 
            this.columnHeader12.Text = "性别";
            // 
            // columnHeader13
            // 
            this.columnHeader13.Text = "国籍";
            // 
            // columnHeader14
            // 
            this.columnHeader14.Text = "明星类型";
            this.columnHeader14.Width = 81;
            // 
            // columnHeader15
            // 
            this.columnHeader15.Text = "出生日期";
            this.columnHeader15.Width = 100;
            // 
            // button4
            // 
            this.button4.Location = new System.Drawing.Point(109, 300);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(373, 23);
            this.button4.TabIndex = 1;
            this.button4.Text = "关闭(&T)";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(576, 335);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.tabControl1);
            this.Name = "Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "后台数据维护";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.frmMain_FormClosed);
            this.Load += new System.EventHandler(this.frmMain_Load);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tabPage4.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private System.Windows.Forms.ColumnHeader columnHeader2;
        private System.Windows.Forms.Button bntAuDelete;
        private System.Windows.Forms.Button bntAuUpdate;
        private System.Windows.Forms.Button bntAut;
        private System.Windows.Forms.ColumnHeader columnHeader3;
        private System.Windows.Forms.ColumnHeader columnHeader4;
        private System.Windows.Forms.ColumnHeader columnHeader5;
        private System.Windows.Forms.ColumnHeader columnHeader6;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        public System.Windows.Forms.ListView lvDitcy;
        private System.Windows.Forms.ColumnHeader columnHeader7;
        private System.Windows.Forms.ColumnHeader columnHeader8;
        private System.Windows.Forms.ColumnHeader columnHeader9;
        public System.Windows.Forms.ListView lvAuton;
        public System.Windows.Forms.ListView lvMuscie;
        private System.Windows.Forms.ColumnHeader columnHeader16;
        private System.Windows.Forms.ColumnHeader columnHeader17;
        private System.Windows.Forms.ColumnHeader columnHeader18;
        private System.Windows.Forms.ColumnHeader columnHeader19;
        private System.Windows.Forms.ColumnHeader columnHeader10;
        private System.Windows.Forms.ColumnHeader columnHeader11;
        private System.Windows.Forms.ColumnHeader columnHeader12;
        private System.Windows.Forms.ColumnHeader columnHeader13;
        private System.Windows.Forms.ColumnHeader columnHeader14;
        private System.Windows.Forms.ColumnHeader columnHeader15;
        private System.Windows.Forms.Button bntMuserDelete;
        private System.Windows.Forms.Button bntMuserUpdate;
        private System.Windows.Forms.Button bntMuserAdd;
        private System.Windows.Forms.ColumnHeader columnHeader20;
        private System.Windows.Forms.ColumnHeader columnHeader21;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.Button bntSave;
        private System.Windows.Forms.Button bntUserDelete;
        private System.Windows.Forms.Button bntUserUpdate;
        private System.Windows.Forms.Button bntUserAdd;
        private System.Windows.Forms.TextBox txtPassWord;
        private System.Windows.Forms.TextBox txtUser;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ListView LvUser;
        private System.Windows.Forms.ColumnHeader columnHeader22;
        private System.Windows.Forms.ColumnHeader columnHeader23;
        private System.Windows.Forms.ColumnHeader columnHeader24;

    }
}

